version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=productdb;Username=postgres;Password=123456
    depends_on:
      - postgres

volumes:
  postgres_data: